# fly.toml app configuration file generated for drippy-ingest on 2026-07-21T16:57:26+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'drippy-ingest'
primary_region = 'lhr'

[build]
[http_service]
  internal_port = 8787
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = false
  min_machines_running = 1

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/v1/health'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
